using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Unary
{
    enum FactId
    {
        GAME_TIME, POPULATION_CAP, POPULATION_HEADROOM, HOUSING_HEADROOM, IDLE_FARM_COUNT, FOOD_AMOUNT, WOOD_AMOUNT, STONE_AMOUNT,
        GOLD_AMOUNT, ESCROW_AMOUNT, COMMODITY_BUYING_PRICE, COMMODITY_SELLING_PRICE, DROPSITE_MIN_DISTANCE,
        SOLDIER_COUNT, ATTACK_SOLDIER_COUNT, DEFEND_SOLDIER_COUNT, WARBOAT_COUNT, ATTACK_WARBOAT_COUNT,
        DEFEND_WARBOAT_COUNT, CURRENT_AGE, CURRENT_SCORE, CIVILIZATION, PLAYER_NUMBER, PLAYER_IN_GAME, UNIT_COUNT,
        UNIT_TYPE_COUNT, UNIT_TYPE_COUNT_TOTAL, BUILDING_COUNT, BUILDING_TYPE_COUNT, BUILDING_TYPE_COUNT_TOTAL,
        POPULATION, MILITARY_POPULATION, CIVILIAN_POPULATION, RANDOM_NUMBER, RESOURCE_AMOUNT, PLAYER_DISTANCE,
        ALLIED_GOAL, ALLIED_SN, RESOURCE_PERCENT, ENEMY_BUILDINGS_IN_TOWN, ENEMY_UNITS_IN_TOWN, ENEMY_VILLAGERS_IN_TOWN,
        PLAYERS_IN_GAME, DEFENDER_COUNT, BUILDING_TYPE_IN_TOWN, UNIT_TYPE_IN_TOWN, VILLAGER_TYPE_IN_TOWN, GAIA_TYPE_COUNT,
        GAIA_TYPE_COUNT_TOTAL, CC_GAIA_TYPE_COUNT, CURRENT_AGE_TIMER, TIMER_STATUS, PLAYERS_TRIBUTE, PLAYERS_TRIBUTE_MEMORY,
        TREATY_TIME
    }
}
