name: main

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1' 
        
    - name: Install dependencies
      run: |
        dotnet restore AoE2Lib\AoE2Lib.csproj
        dotnet restore
      
    - name: Build
      run: dotnet build --configuration Debug --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    # create release if on master
    
    - name: Bump version
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        append_to_pre_release_tag: beta
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        
    - name: Package
      run: |
        dotnet pack AoE2Lib\AoE2Lib.csproj --no-build -p:PackageVersion=${{ steps.tag_version.outputs.new_version }}
        dotnet publish AoE2Lib\AoE2Lib.csproj --output AoE2Lib.${{ steps.tag_version.outputs.new_version }}
        dotnet publish Unary\Unary.csproj --output Unary.${{ steps.tag_version.outputs.new_version }}
        dotnet publish GameRunner\GameRunner.csproj --output GameRunner.${{ steps.tag_version.outputs.new_version }}
        
    - uses: papeloto/action-zip@v1
      with:
        files: Unary.${{ steps.tag_version.outputs.new_version }}
        dest: Unary.${{ steps.tag_version.outputs.new_version }}.zip
        
    - uses: papeloto/action-zip@v1
      with:
        files: GameRunner.${{ steps.tag_version.outputs.new_version }}
        dest: GameRunner.${{ steps.tag_version.outputs.new_version }}.zip
      
    - uses: papeloto/action-zip@v1
      with:
        files: AoE2Lib.${{ steps.tag_version.outputs.new_version }}
        dest: AoE2Lib.${{ steps.tag_version.outputs.new_version }}.zip
     
    - name: Create a GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: ${{ github.ref != 'refs/heads/master' }}
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        files: |
          AoE2Lib\bin\Debug\AoE2Lib.${{ steps.tag_version.outputs.new_version }}.nupkg
          AoE2Lib.${{ steps.tag_version.outputs.new_version }}.zip
          Unary.${{ steps.tag_version.outputs.new_version }}.zip
          GameRunner.${{ steps.tag_version.outputs.new_version }}.zip