name: main

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1' 
        
    - name: Install dependencies
      run: |
        dotnet restore AoE2Lib\AoE2Lib.csproj
        dotnet restore
      
    - name: Build
      run: dotnet build --configuration Debug --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    # create release if on master
    
    - name: Bump version
      if: github.ref == 'refs/heads/master'
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        
    - name: Package
      if: github.ref == 'refs/heads/master'
      run: |
        dotnet pack AoE2Lib\AoE2Lib.csproj --no-build -p:PackageVersion=${{ steps.tag_version.outputs.new_version }}
        dotnet publish ExampleBot\ExampleBot.csproj --output ExampleBot.${{ steps.tag_version.outputs.new_version }}
        dotnet publish GameRunner\GameRunner.csproj --output GameRunner.${{ steps.tag_version.outputs.new_version }}
        
    - uses: papeloto/action-zip@v1
      if: github.ref == 'refs/heads/master'
      with:
        files: ExampleBot.${{ steps.tag_version.outputs.new_version }}
        dest: ExampleBot.${{ steps.tag_version.outputs.new_version }}.zip
        
    - uses: papeloto/action-zip@v1
      if: github.ref == 'refs/heads/master'
      with:
        files: GameRunner.${{ steps.tag_version.outputs.new_version }}
        dest: GameRunner.${{ steps.tag_version.outputs.new_version }}.zip
      
    - name: Create a GitHub release
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        files: |
          AoE2Lib\bin\Debug\AoE2Lib.${{ steps.tag_version.outputs.new_version }}.nupkg
          ExampleBot.${{ steps.tag_version.outputs.new_version }}.zip
          GameRunner.${{ steps.tag_version.outputs.new_version }}.zip