name: main

on: 
  workflow_dispatch:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1' 
    
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '5.0' 
        
    - name: Install dependencies
      run: |
        dotnet restore AoE2Lib\AoE2Lib.csproj
        dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Bump version
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: true
        
    - name: Package
      run: |
        (gc 'Unary\Unary.per').replace('$UNARY_VERSION$', '${{ steps.tag_version.outputs.new_version }}') | Out-File -encoding ASCII Unary\Unary.per
        dotnet tool install -g dotnet-setversion
        setversion -r ${{ steps.tag_version.outputs.new_version }}
        dotnet pack AoE2Lib\AoE2Lib.csproj -c Release -p:PackageVersion=${{ steps.tag_version.outputs.new_version }}
        dotnet publish AoE2Lib\AoE2Lib.csproj -c Release --output AoE2Lib.${{ steps.tag_version.outputs.new_version }}
        dotnet publish Unary\Unary.csproj -c Release --output Unary.${{ steps.tag_version.outputs.new_version }}

    - uses: papeloto/action-zip@v1
      with:
        files: AoE2Lib.${{ steps.tag_version.outputs.new_version }}
        dest: AoE2Lib.${{ steps.tag_version.outputs.new_version }}.zip
        
    - uses: papeloto/action-zip@v1
      with:
        files: Unary.${{ steps.tag_version.outputs.new_version }}
        dest: Unary.${{ steps.tag_version.outputs.new_version }}.zip
     
    - name: Create a GitHub release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
        files: |
          AoE2Lib\bin\Release\AoE2Lib.${{ steps.tag_version.outputs.new_version }}.nupkg
          AoE2Lib.${{ steps.tag_version.outputs.new_version }}.zip
          Unary.${{ steps.tag_version.outputs.new_version }}.zip
